# Archivo de Configuración para dticBKPs
# Generado automáticamente el 2025-07-22 18:35:22
AUTO_AVANZAR_TAREA_MENU = true
TAREAS_CONFIG = [
  {
    id: :xen01_proc_xva,
    menu_texto: "Procesar backups Xen01 (.xva)",
    tipo_proceso: :xva,
    origen: "/media/rmonla/NS8_Disco2/syncs_XEN01",
    destino: "/media/rmonla/NS8_Disco3/dtic_BACKUPS/bkps_XEN01",
    eliminar_origen: true,
    sobrescribir_destino: false,
  },
  {
    id: :pmox1_sinc_ns8,
    menu_texto: "Sincronizar PMOX1 --> NS8 (Local)",
    tipo_proceso: :rclone_sync,
    origen: "pve_PMOX1:/var/lib/vz/dump/",
    destino: "/mnt/ns8Disco2/syncs_PMOX1/",
    eliminar_origen: false,
    sobrescribir_destino: false,
  },
  {
    id: :ns8_proc_bkps_pmox1,
    menu_texto: "Procesar backups PMOX1 (.log/.notes)",
    tipo_proceso: :proxmox_log_notes,
    origen: "/mnt/ns8Disco2/syncs_PMOX1/",
    destino: "/mnt/ns8Disco3/dtic_BACKUPS/bkps_PMOX1/",
    eliminar_origen: true,
    sobrescribir_destino: false,
  },
  {
    id: :pmox2_sinc_ns8,
    menu_texto: "Sincronizar PMOX2 --> NS8 (Local)",
    tipo_proceso: :rclone_sync,
    origen: "pve_PMOX2:/var/lib/vz/dump/",
    destino: "/mnt/ns8Disco2/syncs_PMOX2/",
    eliminar_origen: false,
    sobrescribir_destino: false,
  },
  {
    id: :ns8_proc_bkps_pmox2,
    menu_texto: "Procesar backups PMOX2 (.log/.notes)",
    tipo_proceso: :proxmox_log_notes,
    origen: "/mnt/ns8Disco2/syncs_PMOX2/",
    destino: "/mnt/ns8Disco3/dtic_BACKUPS/bkps_PMOX2/",
    eliminar_origen: true,
    sobrescribir_destino: false,
  },
  {
    id: :pmox3_sinc_ns8,
    menu_texto: "Sincronizar PMOX3 --> NS8 (Local)",
    tipo_proceso: :rclone_sync,
    origen: "pve_PMOX3:/zfsDISCO1/backups/dump",
    destino: "/mnt/ns8Disco2/syncs_PMOX3/",
    eliminar_origen: false,
    sobrescribir_destino: false,
  },
  {
    id: :ns8_proc_bkps_pmox3,
    menu_texto: "Procesar backups PMOX3 (.log/.notes)",
    tipo_proceso: :proxmox_log_notes,
    origen: "/mnt/ns8Disco2/syncs_PMOX3/",
    destino: "/mnt/ns8Disco3/dtic_BACKUPS/bkps_PMOX3/",
    eliminar_origen: true,
    sobrescribir_destino: false,
  },
  {
    id: :ns8_sinc_nube,
    menu_texto: "Sincronizar NS8 --> Nube (Upload)",
    tipo_proceso: :rclone_sync,
    origen: "/mnt/ns8Disco3/dtic_BACKUPS/",
    destino: "rmOneDrive:/dtic_BACKUPS/",
    eliminar_origen: false,
    sobrescribir_destino: false,
  },
]
